build:
  cuda_version: "12.1.1"
  python_packages:
    - "transformers==4.55.2"
    - "mistral_common==1.8.3"
    - "bitsandbytes==0.47.0"
    - "hf-transfer==0.1.9"
    - "inferless==0.2.15"
    - "pydantic==2.11.7"
    - "accelerate==1.10.0"
    - "torch==2.7.0"
    - "torchvision==0.22.0"
    - "mistral-common[opencv]"
